class Sprite{
    constructor(title, id, name, image, type){
        this.title = title;
        this.id = id;
        this.name = name;
        this.image = image;
        this.type = type;
    }
}

var sprites = [
    new Sprite('Bilgewater', 8, 'Bilgewater', 'img/sprites/Bilgewater.png', 'Region'),
    new Sprite('Demacia', 4, 'Demacia', 'img/sprites/Demacia.png', 'Region'),
    new Sprite('Freljord', 0, 'Freljord', 'img/sprites/Freljord.png', 'Region'),
    new Sprite('Ionia', 14, 'Ionia', 'img/sprites/Ionia.png', 'Region'),
    new Sprite('Noxus', 9, 'Noxus', 'img/sprites/Noxus.png', 'Region'),
    new Sprite('Piltover', 5, 'PiltoverZaun', 'img/sprites/PiltoverZaun.png', 'Region'),
    new Sprite('Shadow isles', 1, 'ShadowIsles', 'img/sprites/ShadowIsles.png', 'Region'),
    new Sprite('All regions', 13, 'AllFactions', 'img/sprites/AllFactions.png', 'Region'),
    new Sprite('Targon', 15, 'Targon', 'img/sprites/Targon.png', 'Region'),
    // new Sprite('Shurima', 7, '', 'img/sprites/Shurima.png', 'Region'),
    // new Sprite('Void', 2, '', 'img/sprites/Void.png', 'Region'),
    // new Sprite('Zaun', 20, '', 'img/sprites/Zaun.png','Region'),
    // new Sprite('Bandle city', 10, '', 'img/sprites/BandleCity.png', 'Region'),
    new Sprite('Level up: empty', 10, 'ChampLevelUpIcon1', 'img/sprites/ChampLevelUpIcon1.png', 'Levelup'),
    new Sprite('Level up: half', 6, 'ChampLevelUpIcon2', 'img/sprites/ChampLevelUpIcon2.png', 'Levelup'),
    new Sprite('Level up: full', 2, 'ChampLevelUpIcon3', 'img/sprites/ChampLevelUpIcon3.png', 'Levelup'),
    new Sprite('Common wildcard', 18, 'common', 'img/sprites/common.png', 'Wildcard'),
    new Sprite('Rare wildcard', 19, 'rare', 'img/sprites/rare.png', 'Wildcard'),
    new Sprite('Epic wildcard', 20, 'epic', 'img/sprites/epic.png', 'Wildcard'),
    new Sprite('Champion wildcard', 12, 'champion', 'img/sprites/champion.png', 'Wildcard'),
    new Sprite('Shards', 17, 'currency_shards', 'img/sprites/currency_shards.png', 'Currency'),
    new Sprite('Coin', 3, 'currency_bp', 'img/sprites/currency_bp.png', 'Currency'),
    new Sprite('Burst', 16, 'Burst', 'img/sprites/Burst.png', 'SpellSpeed'),
    new Sprite('Fast', 11, 'Fast', 'img/sprites/Fast.png', 'SpellSpeed'),
    new Sprite('Slow', 7, 'Slow', 'img/sprites/Slow.png', 'SpellSpeed'),
    new Sprite('Attune', '', 'Attune', 'img/sprites/Attune.png', 'Keyword'),
    new Sprite('Aura', '', 'Aura', 'img/sprites/Aura.png', 'Keyword'),
    new Sprite('Barrier', '', 'Barrier', 'img/sprites/Barrier.png', 'Keyword'),
    new Sprite('Capture', '', 'Capture', 'img/sprites/Capture.png', 'Keyword'),
    new Sprite('Challenger', '', 'Challenger', 'img/sprites/Challenger.png', 'Keyword'),
    new Sprite('Deep', '', 'Deep', 'img/sprites/Deep.png', 'Keyword'),
    new Sprite('Double strike', '', 'DoubleStrike', 'img/sprites/DoubleStrike.png', 'Keyword'),
    new Sprite('Elusive', '', 'Elusive', 'img/sprites/Elusive.png', 'Keyword'),
    new Sprite('Ephemeral', '', 'Ephemeral', 'img/sprites/Ephemeral.png', 'Keyword'),
    new Sprite('Fearsome', '', 'Fearsome', 'img/sprites/Fearsome.png', 'Keyword'),
    new Sprite('Fleeting', '', 'Fleeting', 'img/sprites/Fleeting.png', 'Keyword'),
    new Sprite('Frostbite', '', 'Frostbite', 'img/sprites/Frostbite.png', 'Keyword'),
    new Sprite('Fury', '', 'Fury', 'img/sprites/Fury.png', 'Keyword'),
    new Sprite('Immobile', '', 'Immobile', 'img/sprites/Immobile.png', 'Keyword'),
    new Sprite('Invoke', '', 'Invoke', 'img/sprites/Invoke.png', 'Keyword'),
    new Sprite('Last breath', '', 'LastBreath', 'img/sprites/LastBreath.png', 'Keyword'),
    new Sprite('Lifesteal', '', 'Lifesteal', 'img/sprites/Lifesteal.png', 'Keyword'),
    new Sprite('Overwhelm', '', 'Overwhelm', 'img/sprites/Overwhelm.png', 'Keyword'),
    new Sprite('Quick strike', '', 'QuickStrike', 'img/sprites/QuickStrike.png', 'Keyword'),
    new Sprite('Reckless', '', 'Reckless', 'img/sprites/Reckless.png', 'Keyword'),
    new Sprite('Regeneration', '', 'Regeneration', 'img/sprites/Regeneration.png', 'Keyword'),
    new Sprite('Scout', '', 'Scout', 'img/sprites/Scout.png', 'Keyword'),
    new Sprite('Silenced', '', 'Silenced', 'img/sprites/Silenced.png', 'Keyword'),
    new Sprite('Spell Shield', '', 'SpellShield', 'img/sprites/SpellShield.png', 'Keyword'),
    new Sprite('Stunned', '', 'Stunned', 'img/sprites/Stunned.png', 'Keyword'),
    new Sprite('Tough', '', 'Tough', 'img/sprites/Tough.png', 'Keyword'),
    new Sprite('Vulnerable', '', 'Vulnerable', 'img/sprites/Vulnerable.png', 'Keyword'),
    new Sprite('Attack skill mark', '', 'AttackSkillMark', 'img/sprites/AttackSkillMark.png', 'Card Effect'),
    new Sprite('Generic trigger', '', 'GenericTrigger', 'img/sprites/GenericTrigger.png', 'Card Effect'),
    new Sprite('Imbue', '', 'Imbue', 'img/sprites/Imbue.png', 'Card Effect'),
    new Sprite('Play skill mark', '', 'PlaySkillMark', 'img/sprites/PlaySkillMark.png', 'Card Effect'),
    //new Sprite('Augment', '', 'Augment', 'img/sprites/Augment.png', 'Unknown'),
    new Sprite('Landmark', '', 'LandmarkVisualOnly', 'img/sprites/LandmarkVisualOnly.png', 'Keyword')
];